import './globals.css'

import type { Metadata } from 'next'
import { Noto_Sans_JP } from 'next/font/google'

import Header from '@/components/Header'

const notoSansJP = Noto_Sans_JP({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="ja">
      <body className={notoSansJP.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}

export default RootLayout
